name: example_use
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 添加本地包依赖
  lite_simple_ui:
    path: ../

  # 数据库相关依赖
  sqflite: ^2.3.0 # SQLite 数据库
  path: ^1.8.3 # 路径工具
  dio: ^5.4.0 # HTTP 客户端（用于封装数据库操作）

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
